networks:
  aprilrain_queue_network:
    external: true
  aprilrain_db_network:
    external: true
  api-omnistart-network:
    external: true
 
  
services:
  # ============================
  #  Consumer & Publisher (redis/rabbitmq/Restful)
  # ==========================
  generic_consumer:
    build: .
    container_name: generic_consumer
    restart: unless-stopped
    env_file:
      - /home/boncuk/Belgeler/app_environment/aprilrain.env
    networks:
      - aprilrain_queue_network
      - aprilrain_db_network
      - api-omnistart-network

